### ISSUE TITLE
RE: Zero downtime deploys

### ISSUE THREAD

**Issue by jonathanconway** [AusDTO/cga_docs#38]
A point of confusion for me is how CircleCI would work if I was to add multiple apps to `manifest.yml` to enable blue/green deployments. Does CircleCI know to read these multiple apps from `manifest.yml`? My understanding is that `circle.yml` is the file that CircleCI relies upon for configuration. So should I be setting up multiple apps in `circle.yml` then? And how would I do so?

Going to do further research on this and also check with @m-richo.

Would be good to have the above documented. I'm happy to submit a PR for this.

**Comment by tessereth** [comment]
Good question. The simple answer is that the `circle.yml` file determines what CircleCI does, while `manifest.yml` determines what `cf push` does. Presumably, your `circle.yml` file at some point runs the `cf push` command to deploy your code to cloud foundry. The `cf` client tool, reads the `manifest.yml` file (or whichever file is specified with the `-f` flag) and uses that to set all the relevant parameters when it deploys your code. If the manifest file has multiple `applications`, the `cf` client deploys each app one at a time (I'm pretty sure in order but don't quote me on it).

Does that answer your question?

**Comment by tessereth** [comment]
So a more complete answer, you can do zero downtime deploys without specifying multiple applications in your manifest file. If you have a manifest file like:
```
---
buildpack: staticfile_buildpack
memory: 64M
disk-usage: 64M
```
and run the commands
```
cf unmap-route awesome-app-blue awesome-app
cf push awesome-app-blue
cf map-route awesome-app-blue awesome-app
cf unmap-route awesome-app-green awesome-app
cf push awesome-app-green
cf map-route awesome-app-green awesome-app
```
`awesome-app.apps.staging.digital.gov.au` will have zero downtime. If you go to it when your code is not deploying, it will round-robin (or some other scheduling algorithm) between `awesome-app-blue` and `awesome-app-green`. While `awesome-app-blue` is deploying, it will only go to `awesome-app-green` and vice versa.

Now if you have a manifest file with multiple applications like this:
```
---
buildpack: staticfile_buildpack
memory: 64M
disk-usage: 64M
host: awesome-app
applications:
- name: awesome-app-blue
- name: awesome-app-green
```
and you run just
```
cf push
```
It will do effectively the same thing as above, but you don't have to remember to run all the specific commands.

**Comment by jonathanconway** [comment]
Thanks @tessereth! Your description seems to match up to @simonschwartz's [commit](https://github.com/AusDTO/identity-exchange-birth-certificate/commit/389130344d6a04c15d87cd924b42ffff58911ed5). Testing that out to see if it works.

**Comment by jonathanconway** [comment]
On testing this out by deploying a change and continually refreshing while it builds, it seems to have dubious effects.

Some refreshes correctly load the new version.
Some refreshes break completely because the JS resources return 404s.
Some refreshes correctly load the old version.

So the blue/green fix doesn't seem to be solving the "downtime" problem it was intended to solve.

Will investigate further.

**Comment by jonathanconway** [comment]
Ok, looks like the issue must've been with my local browser caching.

When repeatedly loading the page in Chrome Incognito following deployment, it seems to reliably point to the newly deployed version.

I've applied blue-green deployments to the Queensland Birth Certificate prototype. I now feel pretty confident about applying it to the others.

Thanks again @tessereth!!
